### ISSUE TITLE
How to reproduce results?

### ISSUE THREAD

**Issue by sarthmit** [emtiyaz/vmp-for-svae#1]
I am running the file 'experiments_multi_gpu.py' and am getting the following error:

module 'tensorflow.contrib.linalg' has no attribute 'LinearOperatorTriL'

**Comment by nhubi** [comment]
Hi @sarthmit,
it looks like 'LinearOperatorTriL' is deprecated in the most recent version of Tensorflow. We were using [TensorFlow Branch r1.3](https://www.tensorflow.org/versions/r1.3/).
We will soon push detailed environment specifications and explain how to run our code.

**Comment by emtiyaz** [comment]
@sarthmit we have added some explanation in the readme. Hopefully this solves the problem.

**Comment by sarthmit** [comment]
@emtiyaz Thank you very much. I will get to it asap :)

**Comment by emtiyaz** [comment]
@sarthmit I hope the problem is solved. I will close this issue.
