### ISSUE TITLE
limited to small scale data?

### ISSUE THREAD

**Issue by sameerkhurana10** [emtiyaz/vmp-for-svae#3]
Hi,

you mention that your model is limited to small scale data. Didn't Johnson et. al apply their SLDS on mouse videos that contained millions of frames of video data?

Does there model suffer from the same limitation as you mentioned in your paper? If there model is scalable, could you comment on why it is so?

Thanks

**Comment by emtiyaz** [comment]
In the paper we said "our results" are limited to small scale data, not the actual model. This is more of an implementation issue that both Johnson et al. and our method suffer from. The main issue is that an efficient implementation to compute the derivative of Z(phi) is not always available. For example, for linear dynamical system, we used the implementation provided by Johnson et al. but from what I remember it was not GPU based and was very slow for large problems. It is possible that it is not the case for your problem.
