### ISSUE TITLE
Sample command to run wheel dataset ?

### ISSUE THREAD

**Issue by aSingh071954** [emtiyaz/vmp-for-svae#4]
Please can you also add a sample command to run wheel dataset ?

**Comment by nhubi** [comment]
Hi, 
to run the pinwheel dataset, you can open experiments.py, uncomment lines 68-77 and run the file. Does that help?

**Comment by aSingh071954** [comment]
Thanks.

**Comment by aSingh071954** [comment]
How can i run it with GPU, its super slow for pin wheel dataset ?

**Comment by nhubi** [comment]
You can use tensorflow with GPU support to speed it up. Check out the tensorflow installation guide to find out how to install tensorflow-gpu.
